name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

permissions:
  contents: read
  pull-requests: read

jobs:
  # Detect changes to determine which services need building
  changes:
    runs-on: ubuntu-latest
    outputs:
      executor: ${{ steps.changes.outputs.executor }}
      validator: ${{ steps.changes.outputs.validator }}
      miner: ${{ steps.changes.outputs.miner }}
      public-api: ${{ steps.changes.outputs.public-api }}
      workspace: ${{ steps.changes.outputs.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            executor:
              - 'crates/executor/**'
              - 'crates/common/**'
              - 'crates/protocol/**'
              - 'scripts/executor/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
            validator:
              - 'crates/validator/**'
              - 'crates/common/**'
              - 'crates/protocol/**'
              - 'scripts/validator/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
            miner:
              - 'crates/miner/**'
              - 'crates/common/**'
              - 'crates/protocol/**'
              - 'crates/bittensor/**'
              - 'scripts/miner/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
            public-api:
              - 'crates/public-api/**'
              - 'crates/common/**'
              - 'crates/protocol/**'
              - 'scripts/public-api/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
            workspace:
              - 'Cargo.toml'
              - 'Cargo.lock'
              - '.github/workflows/**'

  quick-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "shared-cache"
      - name: Cache system dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-cache-${{ runner.os }}-format-lint
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev xxd
      - name: Generate test key
        run: |
          chmod +x scripts/gen-key.sh
          ./scripts/gen-key.sh
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Quick check builds
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo check -p common -p protocol -p bittensor
      - name: Run clippy on core packages
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo clippy -p common -p protocol -p bittensor --all-targets -- -D warnings -A clippy::result_large_err -A clippy::type_complexity -A clippy::manual_clamp -A clippy::too_many_arguments -A clippy::ptr_arg -A unused_variables -A clippy::manual_async_fn -A dead_code

  # Lint complex packages
  lint-complex:
    runs-on: ubuntu-latest
    needs: quick-checks
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "shared-cache"
      - name: Cache system dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-cache-${{ runner.os }}-lint-complex
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev xxd
      - name: Generate test key
        run: |
          chmod +x scripts/gen-key.sh
          ./scripts/gen-key.sh
      - name: Run clippy on complex packages
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          # Run clippy without vulkan feature to avoid shaderc-sys CMake requirement
          cargo clippy -p executor --all-targets --all-features -- -D warnings -A clippy::result_large_err -A clippy::type_complexity -A clippy::manual_clamp -A clippy::too_many_arguments -A clippy::ptr_arg -A unused_variables -A clippy::manual_async_fn -A dead_code
          # Run clippy on miner
          cargo clippy -p miner --all-targets --all-features -- -D warnings -A clippy::result_large_err -A clippy::type_complexity -A clippy::manual_clamp -A clippy::too_many_arguments -A clippy::ptr_arg -A unused_variables -A clippy::manual_async_fn -A dead_code
          # Run clippy on validator
          cargo clippy -p validator --all-targets --all-features -- -D warnings -A clippy::result_large_err -A clippy::type_complexity -A clippy::manual_clamp -A clippy::too_many_arguments -A clippy::ptr_arg -A unused_variables -A clippy::manual_async_fn -A dead_code
          # Run clippy on public-api
          cargo clippy -p public-api --all-targets --all-features -- -D warnings -A clippy::result_large_err -A clippy::type_complexity -A clippy::manual_clamp -A clippy::too_many_arguments -A clippy::ptr_arg -A unused_variables -A clippy::manual_async_fn -A dead_code

  # Build and test executor
  build-executor:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.executor == 'true' || needs.changes.outputs.workspace == 'true'
    strategy:
      matrix:
        rust-version: [stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "shared-cache"
      - name: Cache system dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-cache-${{ runner.os }}-executor
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev xxd
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Generate test key
        run: |
          chmod +x scripts/gen-key.sh
          ./scripts/gen-key.sh
      - name: Check executor builds
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo check -p executor
      - name: Test executor crate (unit tests only)
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo test -p executor --lib
      - name: Test executor CLI functionality
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo build -p executor
          ./target/debug/executor --help
      - name: Clean up space before Docker build
        run: |
          docker system prune -af
          df -h
      - name: Test Docker build script
        run: |
          chmod +x scripts/executor/build.sh
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          BITTENSOR_NETWORK=test VALIDATOR_PUBLIC_KEY=$VALIDATOR_PUBLIC_KEY ./scripts/executor/build.sh --no-extract

  # Build and test validator
  build-validator:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.validator == 'true' || needs.changes.outputs.workspace == 'true'
    strategy:
      matrix:
        rust-version: [stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "shared-cache"
      - name: Cache system dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-cache-${{ runner.os }}-validator
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler pkg-config libssl-dev xxd
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Generate test key
        run: |
          chmod +x scripts/gen-key.sh
          ./scripts/gen-key.sh
      - name: Check validator builds
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo check -p validator
      - name: Test validator crate (unit tests only)
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo test -p validator --lib
      - name: Test validator CLI functionality
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo build -p validator
          ./target/debug/validator --help
      - name: Clean up space before Docker build
        run: |
          docker system prune -af
          df -h
      - name: Test Docker build script
        run: |
          chmod +x scripts/validator/build.sh
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          BITTENSOR_NETWORK=test VALIDATOR_PUBLIC_KEY=$VALIDATOR_PUBLIC_KEY ./scripts/validator/build.sh --no-extract

  # Build and test miner
  build-miner:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.miner == 'true' || needs.changes.outputs.workspace == 'true'
    strategy:
      matrix:
        rust-version: [stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "shared-cache"
      - name: Cache system dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-cache-${{ runner.os }}-miner
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev xxd
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Generate test key
        run: |
          chmod +x scripts/gen-key.sh
          ./scripts/gen-key.sh
      - name: Check miner builds
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo check -p miner
      - name: Test miner crate (unit tests only)
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo test -p miner --lib
      - name: Test miner CLI functionality
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo build -p miner
          ./target/debug/miner --help
      - name: Clean up space before Docker build
        run: |
          docker system prune -af
          df -h
      - name: Test Docker build script
        run: |
          chmod +x scripts/miner/build.sh
          BITTENSOR_NETWORK=test ./scripts/miner/build.sh --no-extract

  # Build and test public-api
  build-public-api:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.public-api == 'true' || needs.changes.outputs.workspace == 'true'
    strategy:
      matrix:
        rust-version: [stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "shared-cache"
      - name: Cache system dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-cache-${{ runner.os }}-public-api
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev xxd
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Generate test key
        run: |
          chmod +x scripts/gen-key.sh
          ./scripts/gen-key.sh
      - name: Check public-api builds
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo check -p public-api
      - name: Test public-api crate (unit tests only)
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo test -p public-api --lib
      - name: Test public-api CLI functionality
        run: |
          export VALIDATOR_PUBLIC_KEY=$(cat public_key.hex)
          cargo build -p public-api
          ./target/debug/public-api --help
      - name: Clean up space before Docker build
        run: |
          docker system prune -af
          df -h
      - name: Test Docker build script
        run: |
          chmod +x scripts/public-api/build.sh
          BITTENSOR_NETWORK=test ./scripts/public-api/build.sh --no-extract

  # Final status check
  ci-success:
    runs-on: ubuntu-latest
    needs:
      - quick-checks
      - lint-complex
      - build-executor
      - build-validator
      - build-miner
      - build-public-api
    if: always()
    steps:
      - name: Check if all jobs succeeded
        run: |
          if [[ "${{ needs.quick-checks.result }}" == "success" && \
                "${{ needs.lint-complex.result }}" == "success" && \
                ("${{ needs.build-executor.result }}" == "success" || "${{ needs.build-executor.result }}" == "skipped") && \
                ("${{ needs.build-validator.result }}" == "success" || "${{ needs.build-validator.result }}" == "skipped") && \
                ("${{ needs.build-miner.result }}" == "success" || "${{ needs.build-miner.result }}" == "skipped") && \
                ("${{ needs.build-public-api.result }}" == "success" || "${{ needs.build-public-api.result }}" == "skipped") ]]; then
            echo "All CI checks passed!"
            exit 0
          else
            echo "Some CI checks failed!"
            exit 1
          fi
